### ISSUE TITLE
WP-CLI plugin activation breaks due to redirect

### ISSUE THREAD

**Issue by crazyjaco** [multidots/multicollab#40] opened 2021-11-19 16:18 UTC
When activating all plugins on a site using wp-cli, the process breaks after activating multicollab due to a redirect. The remainder of the plugins do not get activated due to this issue.

`Plugin 'xxx' activated.
Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(http://[domain.com]/wp-admin/admin.php?activated=1&page=editorial-comments) called at [/path/to/core/wp-includes/class-wp-hook.php:305]`

**Comment by macr1408** [comment] 2021-11-19 16:38
I can confirm this issue is happening, plugins should not redirect when using WP CLI.

**Comment by benlk** [comment] 2021-12-10 17:58
This bug breaks a build pipeline that activates a number of plugins on a site. The build script activates plugins in alphabetical order, but because of the redirect, the activation script stalls after multicollab, and as a result half the plugins on the site aren't being activated.

**Comment by crazyjaco** [comment] 2022-01-26 21:39
Just noting that this is still an issue. We've had to remove the plugin from our environments due to this problem.

**Comment by poojabhimani12** [comment] 2022-02-07 09:16
Closing this because it's a report for version 2.0.2. Updating a new version will solve this.

**Closed** 2022-02-07 09:16 UTC
Labels: In Review
